site_name: Computer Vision Basics
site_description: "Proyek latihan Computer Vision oleh Hendra"
site_author: Hendra

# TEMA DIRUBAH KE MATERIAL AGAR FITUR DI BAWAHNYA BERFUNGSI
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    # Fitur MkDocs Material lain yang berguna:
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started:
      - Setting SVM: setting-svm.md
      - Setting WSL: wsl-setting.md
      - Install Miniconda: miniconda-install.md
      - Standar Foldering: foldering.md
      - Setting Doc: documentasi-publik.md
  - Project Setup and Configuration:
      - Configuration Overview: config_overview.md
      - Authentication: auth_methods.md
  - Build Process:
      - Overview: build_overview.md
      - Git Integration: git_integration.md
  - Hosting Documentation:
      - Overview: hosting.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  # Pastikan file ini ada di docs/stylesheets/custom.css
  - stylesheets/custom.css

extra:
  version:
    provider: git
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username/repo
